---
# tasks file for apache
- name: install apache2
  apt:
    name: apache2
    update_cache: yes
    state: latest
- name: enabling module read write
  apache2_module:
    name: rewrite
    state: present
  notify:
        - restart apache2
- name: changing apache2 listening port to {{ http_port }}
  lineinfile:
    dest: /etc/apache2/ports.conf
    regexp: "^Listen "
    line: 'Listen {{ http_port }}'
    state: present
  notify:
        - restart apache2
- name: apache2 virtualhost on port 8081
  lineinfile:
    dest: /etc/apache2/sites-available/000-default.conf
    regexp: '^<VirtualHost \*:'
    line: "<VirtualHost *:{{ http_port }}>"
    state: present
  notify:
        - restart apache2
- name: creating a virtual host file
  template:
    src: virtualhost.conf
    dest: /etc/apache2/sites-available/{{ domain }}.conf

- name: a2ensite {{ domain }}
  command: a2ensite {{ domain }}
  args:
    creates: /etc/apache2/sites-enabled/{{ domain }}.conf
  notify:
        - restart apache2

